// Static file — hand-edited, not generated. Bump CACHE_NAME when ASSETS
// changes so the activate handler purges the old cache; content updates to
// existing files don't need a bump (stale-while-revalidate refreshes them).
const CACHE_NAME = 'geocaches-v8';
const ASSETS = [
  "./",
  "./index.html",
  "./style.css",
  "./i18n.js",
  "./app.js",
  "./manifest.json",
  "./icons/pwa/icon-192.png",
  "./icons/pwa/icon-512.png",
  "./icons/pwa/icon-180.png",
  "./icons/pwa/favicon-32.png",
  "./icons/pwa/favicon-16.png",
  "./vendor/leaflet/leaflet.js",
  "./vendor/leaflet/leaflet.css",
  "./vendor/leaflet/images/marker-icon.png",
  "./vendor/leaflet/images/marker-icon-2x.png",
  "./vendor/leaflet/images/marker-shadow.png",
  "./vendor/leaflet/images/layers.png",
  "./vendor/leaflet/images/layers-2x.png",
  "./vendor/attributes/abandonedbuilding-no.png",
  "./vendor/attributes/abandonedbuilding-yes.png",
  "./vendor/attributes/available-no.png",
  "./vendor/attributes/available-yes.png",
  "./vendor/attributes/bicycles-no.png",
  "./vendor/attributes/bicycles-yes.png",
  "./vendor/attributes/boat-no.png",
  "./vendor/attributes/boat-yes.png",
  "./vendor/attributes/bonuscache-no.png",
  "./vendor/attributes/bonuscache-yes.png",
  "./vendor/attributes/cacti-no.png",
  "./vendor/attributes/cacti-yes.png",
  "./vendor/attributes/campfires-no.png",
  "./vendor/attributes/campfires-yes.png",
  "./vendor/attributes/camping-no.png",
  "./vendor/attributes/camping-yes.png",
  "./vendor/attributes/challengecache-no.png",
  "./vendor/attributes/challengecache-yes.png",
  "./vendor/attributes/cliff-no.png",
  "./vendor/attributes/cliff-yes.png",
  "./vendor/attributes/climbing-no.png",
  "./vendor/attributes/climbing-yes.png",
  "./vendor/attributes/cow-no.png",
  "./vendor/attributes/cow-yes.png",
  "./vendor/attributes/danger-no.png",
  "./vendor/attributes/danger-yes.png",
  "./vendor/attributes/dangerousanimals-no.png",
  "./vendor/attributes/dangerousanimals-yes.png",
  "./vendor/attributes/dogs-no.png",
  "./vendor/attributes/dogs-yes.png",
  "./vendor/attributes/fee-no.png",
  "./vendor/attributes/fee-yes.png",
  "./vendor/attributes/field_puzzle-no.png",
  "./vendor/attributes/field_puzzle-yes.png",
  "./vendor/attributes/firstaid-no.png",
  "./vendor/attributes/firstaid-yes.png",
  "./vendor/attributes/flashlight-no.png",
  "./vendor/attributes/flashlight-yes.png",
  "./vendor/attributes/food-no.png",
  "./vendor/attributes/food-yes.png",
  "./vendor/attributes/frontyard-no.png",
  "./vendor/attributes/frontyard-yes.png",
  "./vendor/attributes/fuel-no.png",
  "./vendor/attributes/fuel-yes.png",
  "./vendor/attributes/geotour-no.png",
  "./vendor/attributes/geotour-yes.png",
  "./vendor/attributes/hike_long-no.png",
  "./vendor/attributes/hike_long-yes.png",
  "./vendor/attributes/hike_med-no.png",
  "./vendor/attributes/hike_med-yes.png",
  "./vendor/attributes/hike_short-no.png",
  "./vendor/attributes/hike_short-yes.png",
  "./vendor/attributes/hiking-no.png",
  "./vendor/attributes/hiking-yes.png",
  "./vendor/attributes/horses-no.png",
  "./vendor/attributes/horses-yes.png",
  "./vendor/attributes/hqsolutionchecker-no.png",
  "./vendor/attributes/hqsolutionchecker-yes.png",
  "./vendor/attributes/hunting-no.png",
  "./vendor/attributes/hunting-yes.png",
  "./vendor/attributes/jeeps-no.png",
  "./vendor/attributes/jeeps-yes.png",
  "./vendor/attributes/kids-no.png",
  "./vendor/attributes/kids-yes.png",
  "./vendor/attributes/landf-no.png",
  "./vendor/attributes/landf-yes.png",
  "./vendor/attributes/mine-no.png",
  "./vendor/attributes/mine-yes.png",
  "./vendor/attributes/motorcycles-no.png",
  "./vendor/attributes/motorcycles-yes.png",
  "./vendor/attributes/night-no.png",
  "./vendor/attributes/night-yes.png",
  "./vendor/attributes/nightcache-no.png",
  "./vendor/attributes/nightcache-yes.png",
  "./vendor/attributes/onehour-no.png",
  "./vendor/attributes/onehour-yes.png",
  "./vendor/attributes/parking-no.png",
  "./vendor/attributes/parking-yes.png",
  "./vendor/attributes/parkngrab-no.png",
  "./vendor/attributes/parkngrab-yes.png",
  "./vendor/attributes/partnership-no.png",
  "./vendor/attributes/partnership-yes.png",
  "./vendor/attributes/phone-no.png",
  "./vendor/attributes/phone-yes.png",
  "./vendor/attributes/picnic-no.png",
  "./vendor/attributes/picnic-yes.png",
  "./vendor/attributes/poisonoak-no.png",
  "./vendor/attributes/poisonoak-yes.png",
  "./vendor/attributes/powertrail-no.png",
  "./vendor/attributes/powertrail-yes.png",
  "./vendor/attributes/public-no.png",
  "./vendor/attributes/public-yes.png",
  "./vendor/attributes/quads-no.png",
  "./vendor/attributes/quads-yes.png",
  "./vendor/attributes/rappelling-no.png",
  "./vendor/attributes/rappelling-yes.png",
  "./vendor/attributes/restrooms-no.png",
  "./vendor/attributes/restrooms-yes.png",
  "./vendor/attributes/rv-no.png",
  "./vendor/attributes/rv-yes.png",
  "./vendor/attributes/s_tool-no.png",
  "./vendor/attributes/s_tool-yes.png",
  "./vendor/attributes/scenic-no.png",
  "./vendor/attributes/scenic-yes.png",
  "./vendor/attributes/scuba-no.png",
  "./vendor/attributes/scuba-yes.png",
  "./vendor/attributes/seasonal-no.png",
  "./vendor/attributes/seasonal-yes.png",
  "./vendor/attributes/skiis-no.png",
  "./vendor/attributes/skiis-yes.png",
  "./vendor/attributes/snowmobiles-no.png",
  "./vendor/attributes/snowmobiles-yes.png",
  "./vendor/attributes/snowshoes-no.png",
  "./vendor/attributes/snowshoes-yes.png",
  "./vendor/attributes/stealth-no.png",
  "./vendor/attributes/stealth-yes.png",
  "./vendor/attributes/stroller-no.png",
  "./vendor/attributes/stroller-yes.png",
  "./vendor/attributes/swimming-no.png",
  "./vendor/attributes/swimming-yes.png",
  "./vendor/attributes/teamwork-no.png",
  "./vendor/attributes/teamwork-yes.png",
  "./vendor/attributes/thorn-no.png",
  "./vendor/attributes/thorn-yes.png",
  "./vendor/attributes/ticks-no.png",
  "./vendor/attributes/ticks-yes.png",
  "./vendor/attributes/touristok-no.png",
  "./vendor/attributes/touristok-yes.png",
  "./vendor/attributes/treeclimbing-no.png",
  "./vendor/attributes/treeclimbing-yes.png",
  "./vendor/attributes/uv-no.png",
  "./vendor/attributes/uv-yes.png",
  "./vendor/attributes/wading-no.png",
  "./vendor/attributes/wading-yes.png",
  "./vendor/attributes/water-no.png",
  "./vendor/attributes/water-yes.png",
  "./vendor/attributes/wheelchair-no.png",
  "./vendor/attributes/wheelchair-yes.png",
  "./vendor/attributes/winter-no.png",
  "./vendor/attributes/winter-yes.png",
  "./vendor/attributes/wirelessbeacon-no.png",
  "./vendor/attributes/wirelessbeacon-yes.png",
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(ASSETS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Stale-while-revalidate: serve from cache instantly (works with no connectivity),
// refresh the cache from the network in the background when online.
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.open(CACHE_NAME).then(async (cache) => {
      const cached = await cache.match(req);
      const network = fetch(req)
        .then((res) => { if (res.ok) cache.put(req, res.clone()); return res; })
        .catch(() => cached);
      return cached || network;
    })
  );
});
